base.url=https://www.rudikershaw.com/
spring.datasource.username=${USERNAME}
spring.datasource.password=${PASSWORD}
spring.datasource.url=${DB_URL}?serverTimezone=Europe/London&useSSL=false
spring.datasource.hikari.maximum-pool-size=4
spring.datasource.hikari.maximum-idle=2
spring.datasource.hikari.minimum-idle=1
server.http2.enabled=true
server.compression.enabled=true
server.compression.mime-types=text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,image/png,image/jpeg
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.datasource.hikari.connection-test-query=SELECT 1
twitter.consumer.key=${CONSUMER_KEY:fallback}
twitter.consumer.secret=${CONSUMER_SECRET:fallback}
twitter.access.key=${ACCESS_KEY:fallback}
twitter.access.secret=${ACCESS_SECRET:fallback}
use.ssl=${SSL:true}
reddit.username=${REDDIT_USERNAME:}
maximum.water.alarms=100
app.gone.paths=/donate
